version: '3'

services:

  # 1. Container: Collects question and threads from slack
  slack_collector:
    build: 1_slack_collector/
    volumes:
    - ./1_slack_collector/:/app 
    depends_on:
    - mongodb

  # 2. Container: Stores the raw data from slack
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    
  # 3. Container: ETL job
  etl_job:
    build: 3_etl_job/
    volumes:
      - ./3_etl_job/:/app
    depends_on:
      - mongodb
      - mypg

  # 4. Container: Postgres database server
  mypg:
      image: postgres:12.4
      ports:
        - 5555:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234

  # 5. Container: Slack bot
  slack_bot:
    build: 5_slack_bot/
    volumes:
      - ./5_slack_bot/:/app
    depends_on:
      - mypg

    